### PR TITLE
AC-7994 P1 Add to calendar links displayed as plain urls

### PR DESCRIPTION
**Pull request by geofrocker**
### Changes Introduced in [AC-7994](https://masschallenge.atlassian.net/browse/AC-7994):
- Format to template to html
### Testing:
- Check out this branch
- Masquerade as a mentor and a finalist
- Change their emails to your own before scheduling an office hour.
- Schedule an office hour and reserve it.
- Check the resulting email and notice the calendar links are no longer showing as plain URLs

### CODE REVIEW

**Comment by iankigen** [comment]
Email template code changes look good ✅ 
As it is, the mail is sent in `Content-Type: text/plain` which will not render correctly in the inbox. To fix that you may need to update the mail send function to have something like:
```
from django.template import loader

html_email = loader.render_to_string(
            'path_to_email_template',
            context
        )
MinimalEmailHandler(
            ...
            body=None,
            attach_alternative=[html_email, 'text/html'],
        ).send()
```

**Comment by jonkiparsky** [comment]
@geofrocker Why does this PR reference AC-7816?

**Comment by PrinceDavis** [comment]
> Email template code changes look good ✅
> As it is, the mail is sent in `Content-Type: text/plain` which will not render correctly in the inbox. To fix that you may need to update the mail send function to have something like:
> 
> ```
> from django.template import loader
> 
> html_email = loader.render_to_string(
>             'path_to_email_template',
>             context
>         )
> MinimalEmailHandler(
>             ...
>             body=None,
>             attach_alternative=[html_email, 'text/html'],
>         ).send()
> ```

@geofrocker update on this?

**Comment by geofrocker** [comment]
Updated. The requested changes have been addressed

**Review by iankigen — APPROVED** [review]
Code/QA looks good

Add 2 calendar links should be formatted in HTML links ✅

**Review by PrinceDavis — APPROVED** [review]
- Code Looks good ✅ 
- Email in html format ✅ 
- I however wasn't able view the mail in a mail client as I waited for mail to drop yesterday but never got it from test1 server

**Pull request merged**
