### PR TITLE
AC-7835 - Improve/replace the semantic-release tooling

### PR DESCRIPTION
**Pull request by pbx**
## [AC-7835](https://masschallenge.atlassian.net/browse/AC-7835)

Also see: 
* [accelerate PR](https://github.com/masschallenge/accelerate/pull/2681) 
* [django-accelerator PR](https://github.com/masschallenge/django-accelerator/pull/341)
* [front-end PR](https://github.com/masschallenge/front-end/pull/243)
* [standards PR](https://github.com/masschallenge/standards/pull/153).

### CODE REVIEW

**Review by shanbady — DISMISSED** [review]
I think we also need to resolve references in impact (https://github.com/masschallenge/django-accelerator/blob/development/Makefile#L199) and frontend (https://github.com/masschallenge/front-end/blob/development/Makefile#L216)

**Comment by pbx** [comment]
@shanbady - new PRs posted (and linked from description).

**Comment by jonkiparsky** [comment]
Ideally, our makefile help text should be similar across repos, and commands that are expected to work identically across repos should have identical or nearly-identical help text. 

Can we update the help text for release here to match the updated text on https://github.com/masschallenge/accelerate/pull/2681/files?

**Comment by pbx** [comment]
Good thought Jon, will do.

**Comment by pbx** [comment]
@jonkiparsky - see [my latest comment on the accelerate PR](https://github.com/masschallenge/accelerate/pull/2681#issuecomment-661248634) for my new idea for `Makefile` consistency (TLDR: remove this from the `Makefile`).

**Review by jonkiparsky — APPROVED** [review]

**Comment by pbx** [comment]
@shanbady similar to my comment on the [accelerate PR](https://github.com/masschallenge/accelerate/pull/2681) --  this changes the impact-api `Makefile`, and AC-7997 may also involve Makefile changes, so I'd like to get this merged so as to avoid merge conflicts. Can you please approve, or let me know what you think it still needs? Thanks.

**Review by philophilo — APPROVED** [review]

**Pull request merged**
