### PR TITLE
[AC-7287] Fix the 404 error that is triggered when viewing a single Mentor profile

### PR DESCRIPTION
**Pull request by mkiterian**
### Changes introduced in [AC-7287](https://masschallenge.atlassian.net/browse/AC-7287):
- Upgrade django-graphql-jwt and restore previous graphql authentication backend

### How to test
- Rebuild impact with `make build`
- Run `make run-all-servers`
- While logged in on accelerate on localhost, when you visit impact api at http://localhost:8000/api/accelerator/ and the directory at http://localhost:1234 you should be automatically logged in which does not currently happen on development

### CODE REVIEW

**Review by pbx — DISMISSED** [review]
This is looking good, but I am not able to get the directory running locally. It's been a long while since I've run it. This is not a problem with the submitted code, but is a blocker to me signing off.
```
$ yarn start
yarn run v1.19.2
$ yarn run clean && parcel serve src/index.html
$ rm -rf dist/* .cache
(node:40913) UnhandledPromiseRejectionWarning: Error: Could not locate the bindings file. Tried:
 → /Users/paulbissex/code/STACK-1/front-end/node_modules/deasync/build/deasync.node
 → /Users/paulbissex/code/STACK-1/front-end/node_modules/deasync/build/Debug/deasync.node
 → /Users/paulbissex/code/STACK-1/front-end/node_modules/deasync/build/Release/deasync.node
 → /Users/paulbissex/code/STACK-1/front-end/node_modules/deasync/out/Debug/deasync.node
 → /Users/paulbissex/code/STACK-1/front-end/node_modules/deasync/Debug/deasync.node
 → /Users/paulbissex/code/STACK-1/front-end/node_modules/deasync/out/Release/deasync.node
 → /Users/paulbissex/code/STACK-1/front-end/node_modules/deasync/Release/deasync.node
 → /Users/paulbissex/code/STACK-1/front-end/node_modules/deasync/build/default/deasync.node
 → /Users/paulbissex/code/STACK-1/front-end/node_modules/deasync/compiled/13.2.0/darwin/x64/deasync.node
    at bindings (/Users/paulbissex/code/STACK-1/front-end/node_modules/bindings/bindings.js:88:9)
    at /Users/paulbissex/code/STACK-1/front-end/node_modules/deasync/index.js:34:32
    at Object.<anonymous> (/Users/paulbissex/code/STACK-1/front-end/node_modules/deasync/index.js:76:2)
    at Module._compile (/Users/paulbissex/code/STACK-1/front-end/node_modules/v8-compile-cache/v8-compile-cache.js:178:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1160:10)
    at Module.load (internal/modules/cjs/loader.js:976:32)
    at Function.Module._load (internal/modules/cjs/loader.js:884:14)
    at Module.require (internal/modules/cjs/loader.js:1016:19)
    at require (/Users/paulbissex/code/STACK-1/front-end/node_modules/v8-compile-cache/v8-compile-cache.js:159:20)
    at Object.<anonymous> (/Users/paulbissex/code/STACK-1/front-end/node_modules/parcel-bundler/src/utils/syncPromise.js:1:79)
(node:40913) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:40913) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Comment by mkiterian** [comment]
@pbx not sure what's going on here. Try `yarn clean` on the frontend repo then re-run `make run-server` on impact
Also, verify that the .env variables are set if you've recently re-cloned the frontend repo

**Comment by pbx** [comment]
Did all those steps (I had done them before as well), but still there's nothing on localhost:1234.

**Comment by mkiterian** [comment]
@pbx you may be missing some dependencies run `yarn` to install

**Review by geofrocker — APPROVED** [review]
QA passes and code looks good

**Comment by pbx** [comment]
@mkiterian - sorry to be so high-maintenace here, but `yarn` explodes thus:
```
...
/Users/paulbissex/.node-gyp/13.2.0/include/node/v8.h:3550:37: note: candidate function not viable: requires 3 arguments, but 2 were provided
  V8_WARN_UNUSED_RESULT Maybe<bool> Set(Local<Context> context, uint32_t index,
                                    ^
fatal error: too many errors emitted, stopping now [-ferror-limit=]
1 warning and 20 errors generated.
make: *** [Release/obj.target/fse/fsevents.o] Error 1
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/Users/paulbissex/code/STACK-1/front-end/node_modules/node-gyp/lib/build.js:262:23)
gyp ERR! stack     at ChildProcess.emit (events.js:210:5)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:270:12)
gyp ERR! System Darwin 19.0.0
gyp ERR! command \"/usr/local/Cellar/node/13.2.0/bin/node\" \"/Users/paulbissex/code/STACK-1/front-end/node_modules/node-gyp/bin/node-gyp.js\" \"build\" \"--fallback-to-build\" \"--module=/Users/paulbissex/code/STACK-1/front-end/node_modules/fsevents/lib/binding/Release/node-v79-darwin-x64/fse.node\" \"--module_name=fse\" \"--module_path=/Users/paulbissex/code/STACK-1/front-end/node_modules/fsevents/lib/binding/Release/node-v79-darwin-x64\" \"--napi_version=5\" \"--node_abi_napi=napi\"
gyp ERR! cwd /Users/paulbissex/code/STACK-1/front-end/node_modules/fsevents
gyp ERR! node -v v13.2.0
gyp ERR! node-gyp -v v3.7.0
gyp ERR! not ok 
node-pre-gyp ERR! build error 
node-pre-gyp ERR! stack Error: Failed to execute '/usr/local/Cellar/node/13.2.0/bin/node /Users/paulbissex/code/STACK-1/front-end/node_modules/node-gyp/bin/node-gyp.js build --fallback-to-build --module=/Users/paulbissex/code/STACK-1/front-end/node_modules/fsevents/lib/binding/Release/node-v79-darwin-x64/fse.node --module_name=fse --module_path=/Users/paulbissex/code/STACK-1/front-end/node_modules/fsevents/lib/binding/Release/node-v79-darwin-x64 --napi_version=5 --node_abi_napi=napi' (1)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (/Users/paulbissex/code/STACK-1/front-end/node_modules/fsevents/node_modules/node-pre-gyp/lib/util/compile.js:83:29)
node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:210:5)
node-pre-gyp ERR! stack     at maybeClose (internal/child_process.js:1023:16)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:281:5)
node-pre-gyp ERR! System Darwin 19.0.0
node-pre-gyp ERR! command \"/usr/local/Cellar/node/13.2.0/bin/node\" \"/Users/paulbissex/code/STACK-1/front-end/node_modules/fsevents/node_modules/node-pre-gyp/bin/node-pre-gyp\" \"install\" \"--fallback-to-build\"
node-pre-gyp ERR! cwd /Users/paulbissex/code/STACK-1/front-end/node_modules/fsevents
node-pre-gyp ERR! node -v v13.2.0
node-pre-gyp ERR! node-pre-gyp -v v0.10.0
node-pre-gyp ERR! not ok 
Failed to execute '/usr/local/Cellar/node/13.2.0/bin/node /Users/paulbissex/code/STACK-1/front-end/node_modules/node-gyp/bin/node-gyp.js build --fallback-to-build --module=/Users/paulbissex/code/STACK-1/front-end/node_modules/fsevents/lib/binding/Release/node-v79-darwin-x64/fse.node --module_name=fse --module_path=/Users/paulbissex/code/STACK-1/front-end/node_modules/fsevents/lib/binding/Release/node-v79-darwin-x64 --napi_version=5 --node_abi_napi=napi' (1)"
info This module is OPTIONAL, you can safely ignore this error
```

**Comment by pbx** [comment]
I'm un-assigning myself so that somebody else with a functioning front-end can review it.

**Review by jonkiparsky — DISMISSED** [review]
@mkiterian While signed in on accelerate, I visited http://localhost:1234/directory and got the attached error. 

Screen Shot 2019-12-06 at 11 00 12 AM

**Comment by mkiterian** [comment]
@jonkiparsky did you run `yarn` to install the latest packages?

**Comment by jonkiparsky** [comment]
@mkiterian Re-tested, ran `yarn install`, got the same result

**Comment by pbx** [comment]
**Note** for @jonkiparsky and anybody else have trouble getting clean builds from `yarn` -- on a tip from Herman, I downgraded my local `node` from 13.x to 10.x, which got me out of the `fatal error` state.

I used `nvm` for this: `brew install nvm`, then make the dotfile changes it tells you to, then `nvm install 10 && nvm use 10`

(I haven't picked this back up because I've been working on Django 2 tickets and there's a lot of build overhead switching in and out of that state.)

**Comment by jonkiparsky** [comment]
@pbx this news about node versions seems important and high-value information to share with the team. Also, it seems like a ticket (probably a P0 bug?) for the infrastructure team to take up. 

(I say P0, since it's blocked several engineers so far, and it's cost us a week of tempo on deployments)

**Comment by shanbady** [comment]
I'm still in progress with rebuilding since im switching out of django 2 world. should hopefully have something soon for this.

**Comment by shanbady** [comment]
handing this off to @freshprincekla since he has a running front-end setup. my builds are taking too long

**Review by freshprincekla — APPROVED** [review]
I was able to build the frontend and able to view the mentor profiles. QA passes.

**Pull request merged**
