### PR TITLE
AC-4604: compiled static assets on production api not getting generated correctly

### PR DESCRIPTION
**Pull request by shanbady**
To test this, run make dev locally and open up a developer console and verify that there no 404's for static files. Part of the difficulty here is that this is something that previously worked locally so nothing will visibly change locally but not on production staticfiles will properly load (please note that this was an issue that was manually patched on production to confirm it works so you will not see this on the current prod)

### CODE REVIEW

**Comment by mc-nathan** [comment]
This looks like a short term solution just to get things to work.  If we are going to rely on dev/style.css rather than build/style.min.css, then we should get rid of style.min.css entirely.  However, I think we probably ultimately want the minimized version and we should adjust our deploy process to get that right.  As short term fix I'm willing to approve this, but it needs a follow on ticket to fix it the right way.

**Review by mc-nathan — CHANGES_REQUESTED** [review]
At minimum create a ticket for either correctly creating and deploy the *.min.css files or for eliminating the generation and use of the *.min.css files.

**Comment by mc-nathan** [comment]
Per the ticket the follow on ticket is AC-4603

**Review by mc-nathan — APPROVED** [review]

**Review by knittingarch — APPROVED** [review]
Functional Testing: No 404s present (except the favicon one)
Code: Looks good.
Code Quality: Passes.
Tests: N/A
Coverage: N/A

**Pull request merged**
