### PR TITLE
AC-6277: make run-all-servers does not start directory

### PR DESCRIPTION
**Pull request by VincentHokie**
**Changes introduced in [AC-6277](urlhttps://masschallenge.atlassian.net/browse/AC-6277)**:
- create make targets for starting and stopping our frontend
- expose our frontend to port 1234 automatically

**How to test**:
1 - run `make stop-all-servers`
2 - run `docker ps -a | grep mentor_directory` and get the container_id of `impact-api_mentor_directory` and do `docker rm <id>`
3 - run `docker images | grep mentor_directory` and do `docker rmi <image-id>`

- now checkout AC-6277 on both impact and the directory
- while on impact, run `make run-server`
- wait for the text "FRONTEND BUILD COMPLETE - visit http://localhost:1234 in a browser"
- a this point the directory should be available on localhost:1234 and should reload on code change

@masschallenge/dev-team please note that when the AC-6277 PRs are merged, we will all need to do steps 1 - 3 to ensure you're using these changes.

Steps 1 - 3 can also be used to switch context (i.e. reverse the changes of this PR) after testing this PR.

### CODE REVIEW

**Comment by mkiterian** [comment]
QA Notes:

- [x] Make run-all-servers starts the directory
- [x] Changes on the directory are reflected without having to restart

**Review by pbx — DISMISSED** [review]
The basic functionality is definitely there (i.e. the `run-server` output is as described and the directory server is responsive). 

However the console output is a bit misleading. Specifically the impact-api web server (port 8000) was not responsive at the time the "WEB BUILD COMPLETE" message was printed.

Also, while the directory did start up, the page displayed "Oh no! <script> unable to load due to an `error` event on it" -- is this expected?

**Comment by VincentHokie** [comment]
That language can be improved, on it.

Definitely not expected. When you run the directory as you usually do, do you get this error? Any chance there's a local change on the directory causing this?

**Review by jonkiparsky — APPROVED** [review]
This worked for me, after a few tries, and the code looks reasonable. I'm happy to go forward with it.

**Review by mkiterian — APPROVED** [review]

**Pull request merged**
