### PR TITLE
[AC-4632] API calls for User and Organization connections

### PR DESCRIPTION
**Pull request by jonkiparsky**
To test: become an authenticated API user. Find some users who have memberships in various Startups and Partners, ie 
```
In [6]: from django.contrib.auth import get_user_model

In [7]: User = get_user_model()

In [8]: User.objects.filter(startupteammember__isnull=False, partnerteammember__isnull=False)
Out[8]: <QuerySet [<User: 30-user@example.com>, <User: 30-user@example.com>, <User: 73-user@example.com>,...
```

Submit the following query through postman:
`http://localhost:8000/api/v1/user/XXX/organizations/`
and check that the returned organization ids look right

Try the converse query using some organization ids:

`http://localhost:8000/api/v1/organization/XXX/users/`

and verify that the returned user sets are good. (ie, organization 14039 should have two users on clean db)

### CODE REVIEW

**Comment by yotammanor** [comment]
Updated postman collection with the added two relevant calls (with user/org pair that has a connection) - https://www.getpostman.com/collections/e20616ae9b0b627db313

**Review by yotammanor — CHANGES_REQUESTED** [review]
Functionality works, tests passing. Code in AC-4362 commits look clean and nice.

Still not approving because there are a lot of fpdiff errors, some of which might be from AC-4362 directly:

```
web/impact/impact/models/organization.py:5:1: F401 'django.template.defaultfilters.slugify' imported but unused
web/impact/impact/models/organization.py:47:1: W391 blank line at end of file
web/impact/impact/models/partner.py:6:1: F401 'django.core.validators.RegexValidator' imported but unused
web/impact/impact/models/partner.py:6:1: F401 'django.core.validators.validate_slug' imported but unused
web/impact/impact/models/partner.py:24:74: W291 trailing whitespace
web/impact/impact/models/startup.py:9:1: F401 'django.core.validators.validate_slug' imported but unused
web/impact/impact/models/startup.py:43:74: W291 trailing whitespace
web/impact/impact/tests/factories/partner_factory.py:12:1: E302 expected 2 blank lines, found 1
web/impact/impact/tests/factories/startup_factory.py:13:1: F401 'impact.models.Organization' imported but unused
web/impact/impact/tests/factories/startup_factory.py:26:1: E302 expected 2 blank lines, found 1
web/impact/impact/tests/factories/startup_factory.py:31:51: W291 trailing whitespace
web/impact/impact/tests/factories/startup_factory.py:57:1: W293 blank line contains whitespace
web/impact/impact/tests/test_organization_detail_view.py:6:1: F401 'impact.tests.factories.OrganizationFactory' imported but unused
web/impact/impact/tests/test_organization_detail_view.py:11:1: W293 blank line contains whitespace
web/impact/impact/tests/test_organization_detail_view.py:20:80: E501 line too long (80 > 79 characters)
web/impact/impact/tests/test_organization_detail_view.py:24:48: E712 comparison to True should be 'if cond is True:' or 'if cond:'
web/impact/impact/tests/test_organization_detail_view.py:25:48: E712 comparison to False should be 'if cond is False:' or 'if not cond:'
web/impact/impact/tests/test_organization_detail_view.py:30:80: E501 line too long (80 > 79 characters)
web/impact/impact/tests/test_organization_detail_view.py:34:48: E712 comparison to False should be 'if cond is False:' or 'if not cond:'
web/impact/impact/tests/test_organization_detail_view.py:35:48: E712 comparison to True should be 'if cond is True:' or 'if cond:'
web/impact/impact/tests/test_organization_detail_view.py:35:55: W291 trailing whitespace
web/impact/impact/tests/test_organization_detail_view.py:36:1: W391 blank line at end of file
web/impact/impact/tests/test_organization_detail_view.py:36:1: W293 blank line contains whitespace
web/impact/impact/tests/test_organization_list_view.py:6:1: F401 'impact.tests.factories.OrganizationFactory' imported but unused
web/impact/impact/tests/test_organization_list_view.py:11:1: W293 blank line contains whitespace
web/impact/impact/tests/test_organization_list_view.py:15:1: E302 expected 2 blank lines, found 1
web/impact/impact/tests/test_organization_list_view.py:24:80: E501 line too long (87 > 79 characters)
web/impact/impact/tests/test_organization_list_view.py:34:80: E501 line too long (87 > 79 characters)
web/impact/impact/tests/test_organization_list_view.py:36:1: W391 blank line at end of file
web/impact/impact/tests/test_organization_list_view.py:36:1: W293 blank line contains whitespace
web/impact/impact/tests/test_organization_user_view.py:6:1: F401 'impact.tests.factories.OrganizationFactory' imported but unused
web/impact/impact/tests/test_user_organizations_view.py:6:1: F401 'impact.tests.factories.OrganizationFactory' imported but unused
web/impact/impact/tests/test_user_organizations_view.py:25:80: E501 line too long (83 > 79 characters)
web/impact/impact/tests/test_user_organizations_view.py:26:80: E501 line too long (83 > 79 characters)
web/impact/impact/urls.py:36:80: E501 line too long (80 > 79 characters)
web/impact/impact/urls.py:275:1: W293 blank line contains whitespace
web/impact/impact/v1/views/organization_detail_view.py:4:1: F401 'django.contrib.auth.get_user_model' imported but unused
web/impact/impact/v1/views/organization_detail_view.py:20:1: E302 expected 2 blank lines, found 1
web/impact/impact/v1/views/organization_detail_view.py:23:1: E302 expected 2 blank lines, found 1
web/impact/impact/v1/views/organization_detail_view.py:26:1: E302 expected 2 blank lines, found 1
web/impact/impact/v1/views/organization_detail_view.py:33:1: E302 expected 2 blank lines, found 1
web/impact/impact/v1/views/organization_detail_view.py:60:1: W293 blank line contains whitespace
web/impact/impact/v1/views/organization_list_view.py:4:1: F401 'django.contrib.auth.get_user_model' imported but unused
web/impact/impact/v1/views/organization_users_view.py:4:1: F401 'impact.permissions.V1APIPermissions' imported but unused
web/impact/impact/v1/views/organization_users_view.py:13:1: E302 expected 2 blank lines, found 1
web/impact/impact/v1/views/organization_users_view.py:15:1: W293 blank line contains whitespace
web/impact/impact/v1/views/user_organizations_view.py:5:1: F401 'impact.permissions.V1APIPermissions' imported but unused
web/impact/impact/v1/views/user_organizations_view.py:8:1: F401 'impact.models.Organization' imported but unused
web/impact/impact/v1/views/user_organizations_view.py:17:1: W293 blank line contains whitespace
```

Once AC-4361 is approved and merged into AC-4362 I'll re-review.

**Review by pbx — DISMISSED** [review]
Leaving the start of my review (just lint) because I have to clock out for the afternoon. `make test` did pass for me.

Not noted inline because they weren't lines in the diff: 
* Unused imports at partner.py:6
* Unused `django.core.validators.validate_slug`import at startup.py:9

**Comment by pbx** [comment]
Working on the DB setup tasks to be able to test this. My understanding of what's needed is:

1. checkout AC-4631 on accelerate
2. `resetdb`
3. `dumpdb`
4. in impact-api, `make dbload` that dump

But after I `resetdb` in the VM on that branch, I get a makemigrations complaint. Running `makemigrations` created this:
```
Migrations for 'mc':
  0009_auto_20170811_1729.py:
    - Remove field public_inquiry_email from partner
    - Remove field twitter_handle from partner
    - Remove field website_url from partner
    - Remove field public_inquiry_email from startup
    - Remove field twitter_handle from startup
    - Remove field website_url from startup
    - Alter field name on namedgroup
    - Alter field name on programrole
    - Alter field label on startuplabel
    - Alter field label on userlabel
```

**Review by pbx — CHANGES_REQUESTED** [review]
Working on the DB setup tasks to be able to test this. My understanding of what's needed is:

1. checkout AC-4631 on accelerate ([71d2c25c6](https://github.com/masschallenge/accelerate/commit/71d2c25c6) when I did these steps)
2. `resetdb`
3. `dumpdb`
4. in impact-api, `make dbload` that dump

But after I `resetdb` in the VM on that branch, I get a makemigrations complaint. Running `makemigrations` created this:
```
Migrations for 'mc':
  0009_auto_20170811_1729.py:
    - Remove field public_inquiry_email from partner
    - Remove field twitter_handle from partner
    - Remove field website_url from partner
    - Remove field public_inquiry_email from startup
    - Remove field twitter_handle from startup
    - Remove field website_url from startup
    - Alter field name on namedgroup
    - Alter field name on programrole
    - Alter field label on startuplabel
    - Alter field label on userlabel
```

For the moment I'm proceeding with that (I ran the resulting migration and then continued from step 3 above).

Now I can't seem to make an authorized request. Here' s my workflow in Postman (using the [collection Yotam linked to above](https://www.getpostman.com/collections/e20616ae9b0b627db313))

1. `make superuser` in impact-api and log into the web interface
2. [Create an application](http://localhost:8000/oauth/applications/register/)
3. In Postman, use the "oauth token" request (providing the `client_id` generated in step 2 and the superuser name and password), to generate `access_token`
4. In Postman, use the "v1 user edge organizations get" request to try to see user 30's list of organizations. Confirm that `access_token` is set correctly in Postman "Globals" (eyeball)
5. Get a 403 response, "You do not have permission to perform this action"

**(Postscript: most of the above problems were due to colliding database updates and an unpushed migration; with the new `initial_schema.sql.gz` as of 3be845bcd I was able to test as expected.)**

**Review by pbx — APPROVED** [review]

**Review by yotammanor — APPROVED** [review]
Functionally still good, lint clean, tests passing.
I merged development in, and saw that there was one line of coverage missing. Since it’s a trivial coverage (`__str__` method), I did it myself and pushed. Otherwise good. Merging once travis approves.

**Pull request merged**
