### PR TITLE
[AC-6635] make release issue: tags on impact-api not getting pushed

### PR DESCRIPTION
**Pull request by jonkiparsky**
#### Changes introduced in [AC-6635]()
- tag impact before pushing tags
- minor cleanup to custom tagging mechanism

#### How to test
To test this we could make a release and perform a deploy

--

OR

--

This could be tested locally (but in my opinion, with some hustle) by
- checking this branch out
- running `make release`
- note that a new tag is pushed to impact-api
- another user doing `git fetch` locally should be able to get this tag from the remote

To cleanup
- on accelerate run `make delete-tag tag=<the-tag-that-was-created>`, this will delete the new tag locally and on the remote
- users that tested this branch out should first do this

### CODE REVIEW

**Review by VincentHokie — APPROVED** [review]
✅ LGTM

**Comment by jonkiparsky** [comment]
@pbx Do you want to take a look at this, since you raised the concern?

**Comment by VincentHokie** [comment]
oh wait, found a thing that may cause problems. Version file was updated. Pushing the small change now.

**Comment by VincentHokie** [comment]
Reverted version file, back to a ✅ from me

**Review by shanbady — APPROVED** [review]

**Pull request merged**
