### PR TITLE
AC-7029 - update impact-api dependencies for Django 2

### PR DESCRIPTION
**Pull request by pbx**
## [AC-7029](https://masschallenge.atlassian.net/browse/AC-7029)

**Testing:** Regression. Does everything still work? If you want an area of focus, choose a dependency whose version was bumped and test functionality that involves it.

**Note**: One dependency was not updated, `djangorestframework-jwt`. Since the time box has run out on AC-7029, updating that dependency has been given its own ticket, [AC-7278](https://masschallenge.atlassian.net/browse/AC-7278).

See ticket comments for more details.

### CODE REVIEW

**Comment by pbx** [comment]
Leaving this as WIP while I sort out breakage (five test failures) resulting from switching from the deprecated `djangorestframework-jwt` to the fork `drf-jwt`.

**Comment by pbx** [comment]
Removed the WIP label. Time box on ticket is expended. Remaining work is in [AC-7278](https://masschallenge.atlassian.net/browse/AC-7278).

**Review by philophilo — APPROVED** [review]
code looks good

**Comment by geofrocker** [comment]
QA looks good

**Review by geofrocker — APPROVED** [review]

**Pull request merged**
