### PR TITLE
[AC 5826] - Non-finalist People Profile pages should only be accessible to staff.

### PR DESCRIPTION
**Pull request by iankigen**
## [AC 5826](https://masschallenge.atlassian.net/browse/AC-5826)
**Changes Introduced**
- Finalist and mentors only have access to confirmed finalists profile pages
- Non-finalist People Profile pages are only accessible to staff.

**How to test**

1. Staff should be able to view all profiles: 
- [masquerade as a staff user](http://localhost:8181/admin/simpleuser/user/4668/masquerade/)
- View [finalist profile](http://localhost:1234/people/44670) {should be accessible}
- View [non finalist profile](http://localhost:1234/people/891) {should be accessible}
2. Finalists and mentors should only have access to confirmed finalists profiles
- [masquerade as a mentor/non staff user](http://localhost:8181/admin/simpleuser/user/845/masquerade/)
- View [finalist profile](http://localhost:1234/people/44670) {should be accessible}
- View [non finalist profile](http://localhost:1234/people/891) {should not be accessible}. Expected error message:  "Sorry, You are not allowed to access this page."

### CODE REVIEW

**Review by shanbady — CHANGES_REQUESTED** [review]
The testing instructions could use a bit more detail. Is there a particular user we need to be logged in as when testing? what does the expected output look like?

**Comment by iankigen** [comment]
@shanbady I have updated the testing instructions.

**Review by shanbady — APPROVED** [review]
looks good on my end.

**Review by freshprincekla — APPROVED** [review]
QA passes. Followed steps described in PR and Works as described.

**Pull request merged**
